<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-22T14:15:03 IST" name="Default suite" finished-at="2024-12-22T14:15:08 IST" duration-ms="5269">
    <groups>
    </groups>
    <test started-at="2024-12-22T14:15:03 IST" name="Default test" finished-at="2024-12-22T14:15:08 IST" duration-ms="5269">
      <class name="com.qa.Test.SampleTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.Test.SampleTest@59474f18]" started-at="2024-12-22T14:15:03 IST" name="setup" finished-at="2024-12-22T14:15:05 IST" duration-ms="2179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testFailureScenario()[pri:0, instance:com.qa.Test.SampleTest@59474f18]" started-at="2024-12-22T14:15:05 IST" name="testFailureScenario" description="Simulate Failure Scenario" finished-at="2024-12-22T14:15:05 IST" duration-ms="233" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Simulated failure expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Simulated failure expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at com.qa.Test.SampleTest.testFailureScenario(SampleTest.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFailureScenario -->
        <test-method signature="testHomePageNavigation()[pri:0, instance:com.qa.Test.SampleTest@59474f18]" started-at="2024-12-22T14:15:05 IST" name="testHomePageNavigation" description="Test Home Page Navigation" finished-at="2024-12-22T14:15:07 IST" duration-ms="2436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHomePageNavigation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.Test.SampleTest@59474f18]" started-at="2024-12-22T14:15:07 IST" name="tearDown" finished-at="2024-12-22T14:15:08 IST" duration-ms="359" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.Test.SampleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
